### ISSUE TITLE
scanning subfolders

### ISSUE THREAD

**Issue by AdventurerRussia** [dyphire/mpv-config#13]
is there any way to enable scanning of subfolders in this script? 
using the example of the fuzzydir.lua script
so that you can set --sub-fonts-dir=** and forget about prescribing paths to the fonts folder

**Comment by AdventurerRussia** [comment]
or could you modify your script and add a parameter =**

**Comment by dyphire** [comment]
Unfortunately, due to the limitation of libass, this cannot be achieved.
[libass](https://github.com/libass/libass) (which is in charge of loading the fonts) only supports [a single directory](https://github.com/libass/libass/blob/75a3dbac9bd41842a4d00b0d42c9513e2c8aec67/libass/ass_library.h#L33), thus precluding a plural "paths" option.
Therefore, any path passed to `--sub-fonts-dir` option will overwrite the previous path.

Relevant: https://github.com/mpv-player/mpv/issues/8338#issuecomment-1035882750
