### ISSUE TITLE
Add ArtCNN Shaders 

### ISSUE THREAD

**Issue by Zabooby** [dyphire/mpv-config#76]
They outperform ravu, FSRCNNX and krigbilateral in several tests [here](https://artoriuz.github.io/blog/mpv_upscaling.html).

**Comment by dyphire** [comment]
I have previously tested the performance of the ArtCNN shader, and it shows no significant difference in HD content compared to FSRCNNX. It is only slightly stronger in SD content than FSRCNNX (both perform poorly). There is no reason to add a similar and not significantly improved shader

Don't blindly trust the results of numerical tests, as ravu ar shaders that perform well in that test also perform poorly on SD content. So you can see that the upscaling shaders used as benchmarks are not very recommended in my configuration.

Of course, in terms of upscaling HD content, the credibility of that numerical test is still good.

**Comment by Zabooby** [comment]
By content are you referring to anime or live action? 

Where in your opinion does nnedi3 fit in, similar to FSRCNNX? Good on hd and bad on sd if so why not remove it too? 
Similarly where does FSR's use-case lie?
Would you agree that Anime4k can work better for sd anime but worse on hd in terms of destroying original detail? 

Also what are your thoughts on [Cfl](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction) or the chroma variant of ArtCNN as a chroma replacement for krigbilateral? 

My point in asking these questions is to find the best combination of shaders for anime and live action for both sd and hd content without having a shader folder with 20+ shaders.

**Comment by dyphire** [comment]
> By content are you referring to anime or live action?

both, mainly animation.

> Where in your opinion does nnedi3 fit in, similar to FSRCNNX? Good on hd and bad on sd if so why not remove it too? 

The biggest feature of nnedi3 is that it hardly produces artifacts during upsampling and suppresses the original artifacts in the image, making its versatility irreplaceable. It is surprising that after so many years, there is still no better algorithm to replace it.

The reason why FSRCNNX is retained is because the poor upscaling effect of SD content is almost a common problem among other shaders except for specific shaders, and its effects on HD content is indeed good.

> Similarly where does FSR's use-case lie? Would you agree that Anime4k is worse on hd in terms of destroying original detail, FSRCNNX performs better for me, why do you keep it?

The EASU_rgb variant of FSR often effect similarly to nnedi3 and has lower performance consumption, which is why it is retained.

I also do not recommend using Anime4k for high-definition content as it will disrupt the original details. But its performance on SD content is significantly better than any other shader, with powerful anti aliasing and artifact removal capabilities. You may have noticed that the Anime4k usage I recommended in the configuration does not include its amplification algorithm.

https://github.com/dyphire/mpv-config/blob/014c9dbab084cfe5d6081e4ded6dae389229e42f/mpv.conf#L757-L759

> Also what are your thoughts on [Cfl](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction) or the chroma variant of ArtCNN as a chroma replacement for krigbilateral?

I really don't care much about chromaticity upscaling. The human eye has low sensitivity to chromaticity information and it's not worth investing too much effort and performance in it. Krigbilateral is also unnecessary. The method of inferring chromaticity information through brightness information using Cfl shaders may not work well when there is no strong correlation between brightness and chromaticity.

But once again, I don't care about chromaticity upscaling, so I won't test and compare them. The above is just a subjective judgment.

> My point in asking these questions is to find the best combination of shaders for anime and live action for both sd and hd content without having a shader folder with 20+ shaders.

I won't recommend the best combination for anyone because everyone's preferences are different. Shaders with poor effects on SD content have no impact on people who only watch HD content, and for those who like image sharpening, they will not like shaders like nnedi3. So you can only rely on yourself to choose and use the shader scheme that suits you.
